import time
import uuid
import hashlib
import json
from dataclasses import dataclass, field, asdict
from typing import Dict, Any, Optional

@dataclass
class ExecutionIntent:
    """Authoritative Deterministic Execution Intent Object.
    
    Generated by Strategy + Brain + Risk + Portfolio Brain BEFORE choosing
    Paper vs Live execution adapter. Guarantees 100% parity across all trading decisions.
    """
    execution_intent_id: str = field(default_factory=lambda: f"INTENT-{uuid.uuid4().hex[:8].upper()}")
    strategy_id: str = "SUPERINTELLIGENT_BRAIN_V44_3"
    symbol: str = "BTC/USDT"
    side: str = "BUY"  # BUY / SELL (or LONG / SHORT)
    quantity: float = 0.0
    allocation_usd: float = 0.0
    order_type: str = "MARKET"  # MARKET, LIMIT, TWAP, VWAP, POV, ICEBERG
    execution_algorithm: str = "DIRECT"  # DIRECT, TWAP, VWAP, POV, ICEBERG
    limit_price: Optional[float] = None
    target_price: float = 0.0
    stop_loss_price: Optional[float] = None
    take_profit_price: Optional[float] = None
    max_slippage_bps: float = 5.0
    time_in_force: str = "GTC"  # GTC, IOC, FOK
    leverage: int = 1
    urgency: str = "NORMAL"  # LOW, NORMAL, HIGH, CRITICAL
    thesis: str = "Regime-aligned multi-factor quantitative momentum"
    market_regime: str = "TRENDING_BULL"
    calibrated_win_probability: float = 0.65
    expected_edge_bps: float = 25.0
    risk_snapshot: Dict[str, Any] = field(default_factory=dict)
    portfolio_snapshot: Dict[str, Any] = field(default_factory=dict)
    execution_mode: str = "PAPER"  # PAPER, SHADOW, LIVE, DRY_RUN
    governance_version: str = "GOV_V44_3_STRICT"
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_hash(self) -> str:
        """Deterministic SHA256 hash of strategic decision parameters for parity verification.
        
        Excludes ephemeral timestamp and execution_intent_id to ensure that identical
        market inputs produce an identical deterministic decision hash regardless of mode.
        """
        canonical_dict = {
            "strategy_id": self.strategy_id,
            "symbol": self.symbol,
            "side": self.side.upper(),
            "quantity": round(self.quantity, 6),
            "allocation_usd": round(self.allocation_usd, 2),
            "order_type": self.order_type.upper(),
            "execution_algorithm": self.execution_algorithm.upper(),
            "limit_price": round(self.limit_price, 4) if self.limit_price else None,
            "target_price": round(self.target_price, 4),
            "stop_loss_price": round(self.stop_loss_price, 4) if self.stop_loss_price else None,
            "take_profit_price": round(self.take_profit_price, 4) if self.take_profit_price else None,
            "max_slippage_bps": round(self.max_slippage_bps, 2),
            "time_in_force": self.time_in_force,
            "leverage": self.leverage,
            "urgency": self.urgency,
            "thesis": self.thesis,
            "market_regime": self.market_regime,
            "calibrated_win_probability": round(self.calibrated_win_probability, 4),
            "expected_edge_bps": round(self.expected_edge_bps, 2),
            "governance_version": self.governance_version
        }
        serialized = json.dumps(canonical_dict, sort_keys=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()
