apiVersion: v1
kind: Service
metadata:
  name: lumo-backend-service
  namespace: lumo-trading
spec:
  type: ClusterIP
  selector:
    app: lumo-backend
  ports:
  - port: 8000
    targetPort: 8000
    name: http
