import time
import uuid
import hashlib
import json
from dataclasses import dataclass, field, asdict
from typing import Dict, Any, Optional

@dataclass
class ArbitrageExecutionIntent:
    """Authoritative Deterministic Dual-Leg Arbitrage Execution Intent Object.
    
    Generated by CrossExchangeArbitrageEngine BEFORE choosing Paper vs Live adapter.
    Guarantees 100% parity across spread detection, sizing, and dual-leg risk.
    """
    arbitrage_intent_id: str = field(default_factory=lambda: f"ARB-INTENT-{uuid.uuid4().hex[:8].upper()}")
    symbol: str = "BTC/USDT"
    buy_exchange: str = "BINANCE"
    sell_exchange: str = "BYBIT"
    buy_price: float = 0.0
    sell_price: float = 0.0
    gross_spread_pct: float = 0.0
    net_spread_pct: float = 0.0
    executable_quantity: float = 0.0
    executable_capacity_usd: float = 0.0
    expected_profit_usd: float = 0.0
    max_slippage_bps: float = 2.0
    urgency: str = "HIGH"
    quote_age_ms: float = 0.0
    is_live_quote: bool = True
    execution_mode: str = "PAPER"  # PAPER, SHADOW, LIVE, DRY_RUN
    created_at: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_hash(self) -> str:
        """Deterministic SHA256 hash for arbitrage decision parity."""
        canonical_dict = {
            "symbol": self.symbol,
            "buy_exchange": self.buy_exchange.upper(),
            "sell_exchange": self.sell_exchange.upper(),
            "buy_price": round(self.buy_price, 4),
            "sell_price": round(self.sell_price, 4),
            "gross_spread_pct": round(self.gross_spread_pct, 4),
            "net_spread_pct": round(self.net_spread_pct, 4),
            "executable_quantity": round(self.executable_quantity, 6),
            "executable_capacity_usd": round(self.executable_capacity_usd, 2),
            "max_slippage_bps": round(self.max_slippage_bps, 2)
        }
        serialized = json.dumps(canonical_dict, sort_keys=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()
