from enum import Enum

class CryptoEventType(str, Enum):
    ETF_APPROVAL = "ETF_APPROVAL"
    ETF_REJECTION = "ETF_REJECTION"
    EXCHANGE_HACK = "EXCHANGE_HACK"
    EXCHANGE_OUTAGE = "EXCHANGE_OUTAGE"
    TOKEN_LISTING = "TOKEN_LISTING"
    TOKEN_DELISTING = "TOKEN_DELISTING"
    PARTNERSHIP = "PARTNERSHIP"
    REGULATORY_ACTION = "REGULATORY_ACTION"
    FUNDING_EVENT = "FUNDING_EVENT"
    WHALE_MOVEMENT = "WHALE_MOVEMENT"
    PROTOCOL_EXPLOIT = "PROTOCOL_EXPLOIT"
    TOKEN_UNLOCK = "TOKEN_UNLOCK"
    STABLECOIN_DEPEG = "STABLECOIN_DEPEG"
    BANKRUPTCY = "BANKRUPTCY"
    LITIGATION = "LITIGATION"
    MERGER_ACQUISITION = "MERGER_ACQUISITION"
    UNKNOWN = "UNKNOWN"

class EventImpactSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
